name: xendly_mobile
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  introduction_screen: ^3.0.2
  flutter_svg: ^1.0.3
  pin_code_fields: ^7.4.0
  get: ^4.6.5
  intl: ^0.17.0
  http: ^0.13.4
  get_storage: ^2.0.3
  animated_custom_dropdown: ^1.2.2
  dropdown_below: ^1.0.3
  flutter_remix: ^0.0.3
  shimmer: ^2.0.0
  equatable: ^2.0.5
  dartz: ^0.10.1
  uuid: ^3.0.7
  device_info_plus: ^8.0.0
  flutter_secure_storage: ^7.0.1
  shared_preferences: ^2.0.15
  nigerian_states_and_lga: ^1.0.0
  camera: ^0.10.3
  path_provider: ^2.0.12
  path: ^1.8.2
  permission_handler: ^10.2.0
  firebase_messaging: ^14.3.0
  firebase: ^9.0.3
  firebase_core: ^2.8.0
  flutter_local_notifications: ^8.2.0
  freshchat_sdk: ^0.10.3
  flutter_inappwebview: ^6.0.0-beta.23
  webview_flutter: ^4.2.1
  flutter_face_api: ^4.1.1
  fluttertoast: ^8.2.2
#  flutter_face_api: ^4.1.1
#  webview_flutter: ^4.2.1
#  flutter_inappwebview: ^6.0.0-beta.23

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/fonts/
    - assets/icons/
    - assets/icons/bold/
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: TTFirsNeue
      fonts:
        - asset: assets/fonts/TTFirsNeue-Regular.ttf
          weight: 400
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-Light.ttf
        - asset: assets/fonts/Gilroy-Bold.ttf
        - asset: assets/fonts/Gilroy-Thin.ttf
        - asset: assets/fonts/Gilroy-UltraLight.ttf
        - asset: assets/fonts/Gilroy-Regular.ttf
        - asset: assets/fonts/Gilroy-SemiBold.ttf
        - asset: assets/fonts/Gilroy-ExtraBold.ttf
        - asset: assets/fonts/Gilroy-Black.ttf
        - asset: assets/fonts/Gilroy-Medium.ttf
        - asset: assets/fonts/Gilroy-Heavy.ttf
    - family: Neue Haas
      fonts:
        - asset: assets/fonts/NeueHaasDisplayBlack.ttf
        - asset: assets/fonts/NeueHaasDisplayBold.ttf
        - asset: assets/fonts/NeueHaasDisplayLight.ttf
        - asset: assets/fonts/NeueHaasDisplayMedium.ttf
        - asset: assets/fonts/NeueHaasDisplayRoman.ttf
        - asset: assets/fonts/NeueHaasDisplayThin.ttf
        - asset: assets/fonts/NeueHaasDisplayXThin.ttf
        - asset: assets/fonts/NeueHaasDisplayXXThin.ttf
    - family: Plus Jakarta Sans
      fonts:
        - asset: assets/fonts/Plus_Jakarta_Sans/PlusJakartaSans-Bold.ttf
        - asset: assets/fonts/Plus_Jakarta_Sans/PlusJakartaSans-ExtraBold.ttf
        - asset: assets/fonts/Plus_Jakarta_Sans/PlusJakartaSans-ExtraLight.ttf
        - asset: assets/fonts/Plus_Jakarta_Sans/PlusJakartaSans-Light.ttf
        - asset: assets/fonts/Plus_Jakarta_Sans/PlusJakartaSans-Medium.ttf
        - asset: assets/fonts/Plus_Jakarta_Sans/PlusJakartaSans-Regular.ttf
        - asset: assets/fonts/Plus_Jakarta_Sans/PlusJakartaSans-SemiBold.ttf
    - family: iconsax
      fonts:
        - asset: assets/icons/iconsax.ttf
